# test_log.py
from log_to_chain import log_failure_to_chain

log_failure_to_chain("Test failure from new setup", 1.4)
